--- ../../output/build/linux-5.10/arch/m68k/coldfire/Makefile	2020-12-13 23:41:30.000000000 +0100
+++ ../../changed_files/linux-3.x/arch/m68k/coldfire/Makefile	2020-12-15 17:04:15.563696026 +0100
@@ -19,6 +19,7 @@
 obj-$(CONFIG_M5206)	+= m5206.o timers.o intc.o reset.o
 obj-$(CONFIG_M5206e)	+= m5206.o timers.o intc.o reset.o
 obj-$(CONFIG_M520x)	+= m520x.o pit.o intc-simr.o reset.o
+obj-$(CONFIG_KSCF52xx) += kscf52xx.o timers.o intc-simr.o reset.o
 obj-$(CONFIG_M523x)	+= m523x.o pit.o dma_timer.o intc-2.o reset.o
 obj-$(CONFIG_M5249)	+= m5249.o timers.o intc.o intc-5249.o reset.o
 obj-$(CONFIG_M525x)	+= m525x.o timers.o intc.o intc-525x.o reset.o
